version: "3.9"
services:
  dosin_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage
    networks:
      - dosidat-network
    depends_on:
      - mysql
    environment:
      APP_ENV: local
      APP_KEY: base64:BVe4tY+y19aPzozTBZOGfaBfaGlD52y981fvjIfbYxM=
      APP_DEBUG: true
      APP_URL: http://localhost
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: project_laravel
      DB_USERNAME: root
      DB_PASSWORD: root

  mysql:
    image: mysql:8.0.36-debian
    container_name: laravel-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project_laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - dosidat-network
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    networks:
      - dosidat-network
    depends_on:
      - dosin_server

networks:
  dosidat-network:
    external: true

volumes:
  mysql_data:
